# Project information
site_name: PGSync
site_url: https://pgsync.com
site_author: Tolu Aina
site_description: >-
  PGSync simplifies your data pipeline by integrating Postgres into Elasticsearch.

# Repository
repo_name: toluaina/pg-sync
repo_url: https://github.com/toluaina/pg-sync
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2016 - 2020 Tolu Aina

# Configuration
theme:
  name: material
  palette:
    scheme: slate
    primary: orange
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
- toc:
    permalink: true
- markdown.extensions.codehilite:
    guess_lang: false
- admonition
- codehilite
- extra
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_div_format ''
- pymdownx.tabbed

# Customization
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/pgsync
    - icon: fontawesome/brands/github
      link: https://github.com/toluaina/pg-sync
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/pgsync/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/pgsync2
    - icon: fontawesome/solid/at
      link: mailto:contact@pgsync.com

extra_css:
- css/termynal.css
extra_javascript:
- js/termynal.js
- js/custom.js

# Page tree
nav:
- PGSync: index.md
- Features: features/index.md
- Getting started:
  - getting-started/setup.md
  - getting-started/installation.md
  - getting-started/running.md
- Environment variables: environment-variables/index.md
- Schema definition: schema/index.md
- Tutorial - User Guide:
  - tutorial/table-with-single-child-node.md
  - tutorial/table-with-multiple-children.md
  - tutorial/using-labels.md
  - tutorial/selecting-schema.md
  - tutorial/relationship-with-object-variant.md
  - tutorial/relationship-with-scalar-variant.md
  - tutorial/relationship-with-one-to-one-type.md
  - tutorial/relationship-with-one-to-many-type.md
  - tutorial/relationship-with-through-tables.md
  - tutorial/transform-nodes.md
  - tutorial/json-types.md
- Advanced - User Guide:
  - advanced/re-indexing.md
